### PR TITLE
fix: change primary key for `LetterSound_Letter` and `LetterSound_Sound`

### LINKED ISSUE #141: `UNIQUE constraint failed` when downloading Letter-Sounds
Occurs when downloading English content:

```java
2025-02-19 14:37:22.265 10761-10804 ai.elimu.c...Fragment$3 ai.elimu.content_provider.debug      I  letterSoundGson.getId(): 30
2025-02-19 14:37:22.269 10761-10804 ai.elimu.c...Fragment$3 ai.elimu.content_provider.debug      I  Stored LetterSound in database with ID 30
2025-02-19 14:37:22.269 10761-10804 ai.elimu.c...Fragment$3 ai.elimu.content_provider.debug      I  letterGsons.size(): 2
2025-02-19 14:37:22.270 10761-10804 ai.elimu.c...Fragment$3 ai.elimu.content_provider.debug      I  letterGson.getId(): 20
2025-02-19 14:37:22.272 10761-10804 ai.elimu.c...Fragment$3 ai.elimu.content_provider.debug      I  Stored LetterSound_Letter in database. LetterSound_id: 30, letters_id: 20
2025-02-19 14:37:22.273 10761-10804 ai.elimu.c...Fragment$3 ai.elimu.content_provider.debug      I  letterGson.getId(): 20
2025-02-19 14:37:22.277 10761-10804 AndroidRuntime          ai.elimu.content_provider.debug      E  FATAL EXCEPTION: pool-2-thread-1
                                                                                                    Process: ai.elimu.content_provider.debug, PID: 10761
                                                                                                    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: LetterSound_Letter.LetterSound_id, LetterSound_Letter.letters_id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
                                                                                                    	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                                                    	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:961)
                                                                                                    	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
                                                                                                    	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
                                                                                                    	at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:64)
                                                                                                    	at ai.elimu.content_provider.room.dao.LetterSound_LetterDao_Impl.insert(LetterSound_LetterDao_Impl.java:61)
                                                                                                    	at ai.elimu.content_provider.ui.letter_sound.LetterSoundsFragment$3.run(LetterSoundsFragment.java:151)
```

https://github.com/user-attachments/assets/048a4c58-76cd-45fe-9745-b03172667920

### PR DESCRIPTION
**Pull request by jo-elimu**
- [x] `LetterSound_Letter`
   https://github.com/elimu-ai/content-provider/pull/206/commits/f6df26f14d3b6d32e71b466f38397f2b3d54830b
- [x] `LetterSound_Sound`
   https://github.com/elimu-ai/content-provider/pull/206/commits/b1726c337a8e72ddfc0948378426dde283dd02e6

### Issue Number

* Resolves #141

### Purpose

* 

### Technical Details

* 

### Testing Instructions

Tested the DB migration, and here is the log output:

```
2025-04-01 23:06:21.624 12775-12775 ai.elimu.c...rsFragment ai.elimu.content_provider.debug      I  response: Response{protocol=http/1.1, code=200, message=OK, url=http://eng.elimu.ai/rest/v2/content/letters}
2025-04-01 23:06:21.624 12775-12775 ai.elimu.c...rsFragment ai.elimu.content_provider.debug      I  letterGsons.size(): 55
2025-04-01 23:06:21.624 12775-12775 ai.elimu.c...rsFragment ai.elimu.content_provider.debug      I  processResponseBody
2025-04-01 23:06:21.625 12775-12880 ai.elimu.c...rsFragment ai.elimu.content_provider.debug      I  run
2025-04-01 23:06:21.750 12775-12880 ai.elimu.c....RoomDb$22 ai.elimu.content_provider.debug      I  migrate (27 --> 28)
2025-04-01 23:06:21.750 12775-12880 ai.elimu.c....RoomDb$22 ai.elimu.content_provider.debug      I  sql: DROP TABLE `LetterSound_Letter`
2025-04-01 23:06:21.754 12775-12880 ai.elimu.c....RoomDb$22 ai.elimu.content_provider.debug      I  sql: CREATE TABLE IF NOT EXISTS `LetterSound_Letter` (`LetterSound_id` INTEGER NOT NULL, `letters_id` INTEGER NOT NULL, `letters_ORDER` INTEGER NOT NULL, PRIMARY KEY(`LetterSound_id`, `letters_ORDER`))
2025-04-01 23:06:21.755 12775-12880 ai.elimu.c....RoomDb$23 ai.elimu.content_provider.debug      I  migrate (28 --> 29)
2025-04-01 23:06:21.755 12775-12880 ai.elimu.c....RoomDb$23 ai.elimu.content_provider.debug      I  sql: DROP TABLE `LetterSound_Sound`
2025-04-01 23:06:21.756 12775-12880 ai.elimu.c....RoomDb$23 ai.elimu.content_provider.debug      I  sql: CREATE TABLE IF NOT EXISTS `LetterSound_Sound` (`LetterSound_id` INTEGER NOT NULL, `sounds_id` INTEGER NOT NULL, `sounds_ORDER` INTEGER NOT NULL, PRIMARY KEY(`LetterSound_id`, `sounds_ORDER`))
```

> [!NOTE]
> It is worth noting that the database migration will not happen until the user triggers a database interaction. This means that installing the new app version, launching it and simply going to the default `HomeFragment` is not enough; To trigger the database migration script, you will have to go to another fragment which triggers database interaction. For example the `Letters` tab.

### Screenshots

*
Screenshot 2025-04-01 223438

## Summary by CodeRabbit

- **New Features**
  - Upgraded the app’s database schema to the latest version, enhancing data integrity and migration reliability.
  - Improved the handling of letter ordering, ensuring a more consistent and accurate presentation of content.

### CODE REVIEW

File: app/src/main/java/ai/elimu/content_provider/ui/letter_sound/LetterSoundsFragment.kt [hunk 1]
```diff
@@ -132,11 +132,12 @@ class LetterSoundsFragment : Fragment() {
                     // Store all the LetterSound's letters in the database
                     val letterGsons = letterSoundGson.letters
                     Log.i(TAG, "letterGsons.size(): " + letterGsons.size)
-                    for (letterGson in letterGsons) {
+                    for ((index, letterGson) in letterGsons.withIndex()) {
                         Log.i(TAG, "letterGson.getId(): " + letterGson.id)
                         val letterSound_Letter = LetterSound_Letter()
                         letterSound_Letter.letterSound_id = letterSoundGson.id
                         letterSound_Letter.letters_id = letterGson.id
+                        letterSound_Letter.letters_ORDER = index
```
Comment (jo-elimu) [inline app/src/main/java/ai/elimu/content_provider/ui/letter_sound/LetterSoundsFragment.kt:140]: This assumes that the REST API returns a letters array sorted in the correct order.
